## Imports

In [1]:
import numpy as np

## Network Class

In [16]:
"""
Simple_NN
Class to create a simple neural network
    Learning Algorithm: stochastic gradient descent with backpropagation
    Activation Function: sigmoid
    Cost Function: MSE
"""
class Simple_NN(object):
    """ 
    INITIALIZE THE NETWORK
    """
    def __init__(self, layers, activation_function="sigmoid", cost_function="MSE"):
        """
        self.layers is a list of numbers where the ith number how many neurons are in
        the ith layer of the network.
        """
        self.layers = layers;
        self.num_layers = len(layers);
        
        """
        self.weights[Layer - 1, input_neuron, output_neuron] = 
                                            List of weight matrices for each layer.                      
        self.biases[Layer - 1, neuron] = 
                                            List of vectors with biases for each neuron  
        FOR EXAMPLE:
            self.weights[layer, j, i] = weight going into the jth neuron of the lth layer
                                    from the ith neuron of the (l-1)st layer 
            self.biases[layer, k] = bias on the kth nuron of the lth layer
        NOTE: layer 0 is the input layer, so self.weights[0] is the weights going into layer 1
        """
        self.weights = [];
        self.biases = [];
        self.Z = [];
        self.activations = [];
        # Create matrices with correct dimensions 
        for layer_num in range(1, self.num_layers):
            self.weights.append(np.random.randn(layers[layer_num], layers[layer_num - 1]));
            self.biases.append(np.random.randn(layers[layer_num]));
        """
        self.activation = string specifying what activation function the neurons will use. 
            The options are:
            sigmoid (default)
        self.cost_function = string specifying hat cost function will be used for the 
            network.
            The options are:
            MSE (default)
        """
        self.activation_function = activation_function;
        self.cost_function = cost_function;
        self.errors = [];
        self.gradC_b = [];
        self.gradC_w = [];
 
    """
    TRAINING
    Train the network using stochastic gradient descent and backpropagation.
    Training data should be given in the following format:
        [x11, x12, ..., x1i, y1
         x21, x22, ..., x2i, y2
         ...
         xm1, xm1, ..., xmi, ym]
    Where each row corrsponds to a training example with i data points
    """
    def train(self, training_data, batch_size, num_epochs, learning_rate):
        for epoch in range(num_epochs):
            print("EPOCH: %d" % epoch);
            # Randomize the order of training examples
            np.random.shuffle(training_data);
            # Separate inputs from outputs
            inputs = training_data[:, :-1]
            outputs = training_data[:, -1];
            # For each epoch, loop through each batch to use as training data
            for batch in range(len(training_data))[::batch_size]:
                """
                For each batch, we calculate activations and use the backpropagation
                algorithm to change the weights and biases using gradient descent
                Create matrix out of all training inputs in the batch
                To apply W to all input vectors, we can multiply WX where
                X is the ixm matrix containing all m training examples as columns
                """
                X = inputs[batch : batch + batch_size];
                X = np.transpose(X);
                Y = outputs[batch : batch + batch_size];
                # FEEDFORWARD
                self.evaluate(X);
                # BACKPROPAGATION
                self.backpropagate(X, Y);
                # GRADIENT DESCENT
                self.grad_descent();
    
    """
    EVALUATE
    Takes an input vector X and computes the output of the network
    """
    def evaluate(self, X):
        """
        self.Z[layer, neuron, training_example] = 
                        List of vectors with weighted inputs to the neurons
        self.activations[layer, neuron, training_Example] = 
                        List of vectors with activations for each neuron
        """
        self.Z = [];
        self.activations = [];
        # Calclate outputs going forwards through the network
        for layer in range(self.num_layers - 1):
            if layer == 0:
                # Feed inputs to the network
                prev_activations = X;
            else:
                prev_activations = self.activations[layer - 1];
            # Bias matrix where each column is a copy of the bias vector is needed
            # to add bias terms for each training example. 
            one_vector = np.ones(batch_size);
            bias_matrix = np.outer(self.biases[layer], one_vector);  
            self.Z.append(np.dot(self.weights[layer], prev_activations) + bias_matrix);
            self.activations.append(self.activation(self.Z[layer]));
        
    """
    BACKPROPAGATE
    Using input vector X and output vector Y, calculates the following instance variables:
        self.errors[layer, neuron, training_example] - error in each neuron
        self.gradC_b[layer] - average gradient wrt biases over all training examples
        self.gradC_w[layer, input_neuron, output_neuron] - average gradient wrt weights
    """
    def backpropagate(self, X, Y):
        # Calculate output error matrix so the [i, j]th entry contains the
        # error for the ith neuron in the output layer for the jth training
        # example
        output_error = np.multiply(
                             self.cost_derivative(self.activations[-1], Y),
                             self.activation_derivative(self.Z[-1]));
        # Backpropogate: we create the errors matrix which is indexed
        # in the form errors[layer, neuron, training_example]
        self.errors = [output_error];
        # Note that in the loop, we use negative subscripts to go through the 
        # layers from output towards input. We therefore start at layer [-2], the
        # second to last layer
        for layer in range(2, self.num_layers):               
            # For each layer, calculate errors in previous layer
            previous_errors = np.multiply(
                                np.dot(
                                    np.transpose(self.weights[-layer + 1]),
                                    self.errors[0]), 
                                self.activation_derivative(self.Z[-layer])); 
            # Add previous errors to the beginning of the error matrix list
            self.errors.insert(0, previous_errors);
        # Calculate gradients of cost function
        self.gradC_b = [];
        self.gradC_w = [];
        for layer in range(self.num_layers - 1):
            """
            gradC_b[layer, neuron] = 
            Gradient of cost wrt biases for a layer is just the
            vector of errors for that layer.
            When we compute the average over all training examples using 
            np.average(matrix, 1), we get a column vector. In order to
            correctly subtract this from the row-vector of biases, 
            we transpose the gradient vectors.
            """
            self.gradC_b.append(np.average(self.errors[layer],1));
            """
            sum_of_weights[layer, j, k] will contain the partial derivative 
            of cost wrt the weight from the kth neuron in layer - 1 to the jth
            neuron in layer summed over all training examples. That is,
            sum_of_weightes[layer, j, k] = [sum over training examples dC/dw_j,k]
            """
            if (layer == 0):
               prev_activations = X;
            else:
               prev_activations = self.activations[layer - 1];
            sum_of_weights = np.dot(
                                    self.errors[layer],
                                    np.transpose(prev_activations));
            """
            gradC_w [layer, input_neuron, output_neuron] is also 
                averaged over all traininge examples in the batch
            """
            self.gradC_w.append((1 / batch_size) * sum_of_weights);
    
    """
    GRADIENT DESCENT
    Use the gradients computed in backpropagate() to update the weights and
    biases of the network.
    """
    def grad_descent(self):
        for layer in range(self.num_layers - 1):
            self.biases[layer] = np.subtract(self.biases[layer],
                        np.transpose(np.multiply(learning_rate, self.gradC_b[layer])));
            self.weights[layer] = np.subtract(self.weights[layer],
                        np.multiply(learning_rate, self.gradC_w[layer]));
        
    """ 
    ACTIVATION FUNCTION
    For this network, we use the sigmoid function to calculate neuron activation
    In general, we assume the input z will be a matrix where the [i,j]th entry is the
    ith neuron in the jth training example
    """      
    def activation(self, z):
        if (self.activation_function == "sigmoid"):
            return 1.0 / (1 + np.exp(-z));
    
    def activation_derivative(self, z):
        if (self.activation_function == "sigmoid"):
            return np.multiply((1 - self.activation(z)), self.activation(z));
    """
    COST FUNCTION
    We assume that activations is a 2D matrix where each column corresponds to the activations
    for a specific training example and each row corresponds to a specific neuron

    We assume for now that outputs for the network are disjoint categories, so only
    one output neuron should fire at a time. the output_matrix function turns the output
    vector where each entry corresponds to a training example into 
    
    Both calculate_cost and cost_derivative return a row vector where the ith entry
    is the cost/cost derivative for training example i
    """
    def output_matrix(self, activations, outputs):
        # output_matrix[neuron, training_example]
        output_matrix = np.zeros((activations.shape[0], outputs.shape[0]));
        for training_example, output in enumerate(outputs):
            output_matrix[output, training_example] = 1;
        return output_matrix;
    
    def calculate_cost(self, activations, outputs):
        outputs_matrix = self.output_matrix(activations, outputs);
        if (self.cost_function == "MSE"):
            squared_errors = np.square(activations - output_matrix);
            # Average sum of squared errors over each training example
            return 0.5 * np.average(np.sum(squared_errors, 0));
    """
    Derivative of cost functions with respect to activations
    Each entry [i, j] in the resulting matrix will be the gradient of the cost function
    with respect to the activation of the ith neuron in the jth training example
    """
    def cost_derivative(self, activations, outputs):
        output_matrix = self.output_matrix(activations, outputs);
        if (self.cost_function == "MSE"):
            return (activations - output_matrix);
       
    """ 
    TODO: 
        predict(data)
        test(testing_data)
    """
    
    def print_network(self):
        print("Number of layers: ");
        print(self.num_layers);
        print("Weights: ")
        for layer in self.weights:
            print(layer)
        print("\nBiases:" )
        for layer in self.biases:
            print(layer)
        print("\nWeighted Inputs:")
        for layer in self.Z:
            print(layer)
        print("\nActivations:")
        for layer in self.activations:
            print(layer);
        print("\nErrors:")
        for layer in self.errors:
            print(layer)
        print("\nBias Gradients:")
        for layer in self.gradC_b:
            print(layer)
        print("\nWeight Gradients")
        for layer in self.gradC_w:
            print(layer)

In [20]:
"""
TEST NETWORK CREATION
"""
test = Simple_NN([3, 6, 5, 10, 4]);
random_data = np.matrix('1, 2, 3, 0; 11, 12, 13, 1; 21, 22, 23, 2; 31, 32, 33, 3')
batch_size = 2;
num_epochs = 3;
learning_rate = 0.5;

print("\n\nBEGIN TRAINING\n")

test.train(random_data, batch_size, num_epochs, learning_rate);

print("After training");
test.print_network();





BEGIN TRAINING

EPOCH: 0
EPOCH: 1
EPOCH: 2
After training
Number of layers: 
5
Weights: 
[[ 0.3758496  -0.34491384 -0.38985529]
 [-0.89501029 -0.67887755  1.76574667]
 [ 0.09788202  0.31368507 -0.94465044]
 [-0.27211998  1.49180206 -1.88507685]
 [-2.15503294 -0.33280391  1.84987749]
 [ 0.75713262 -0.02851398  0.76095766]]
[[ 0.94363366 -1.06696093 -1.025694   -0.60055595 -0.05856035  0.26025595]
 [ 1.51779832 -0.0303841   0.03658494 -0.02603157  0.18149658  2.4174996 ]
 [-0.1675492  -0.34339186 -2.07730675  1.11308277 -1.29875818 -1.46739986]
 [ 1.04159957 -1.16847651 -0.22745171 -1.65518118 -0.22472392  0.03541468]
 [ 0.43227309  1.47173115  1.19551283  0.65828623  1.49929719 -1.11640192]]
[[-0.89781886 -0.35802998  0.94906852  1.26537511 -0.31954126]
 [ 0.65323819  0.98217063 -1.00264479  0.70754262  0.72983851]
 [-0.9388299   1.12934797 -0.00365666  0.67244556  0.29024175]
 [ 0.46301718 -0.51307976  0.42640043  0.48235926  0.97467606]
 [-0.09841142 -0.99478782 -0.46121232 -0.21602