## Imports

In [4]:
import numpy as np

## Network Class

In [143]:
"""
Simple_NN
Class to create a simple neural network
    Activation Function: sigmoid
    Learning Algorithm: stochastic gradient descent with backpropagation
    Cost Function: Mean squared error
"""
class Simple_NN(object):
    """ 
    INITIALIZE THE NETWORK
    """
    def __init__(self, layers, activation_function="sigmoid"):
        """
        self.layers is a list of numbers where the ith number how many neurons are in
        the ith layer of the network.
        """
        self.layers = layers;
        self.num_layers = len(layers);
        
        """
        self.weights[Layer - 1, input_neuron, output_neuron] = 
            matrix of weights for the entire network with indices
            FOR EXAMPLE: The weight on the edge between neuron 5 in layer 2 and 
                neuron 3 in layer 3 is self.weights[3,5,3]     
        self.biases[Layer - 1, neuron] = matrix containing bias vectors for each layer
            First dimension = layer number, with biases for layer 1 in self.biases[0,:]
            Second dimension = which neuron in the layer
            FOR EXAMPLE: The bias on the 3rd neuron in the 5th layer is in self.biases[6, 3]    
        self.Z = weighted inputs to each neuron.
            Z[i, j] is the weighted input to the ith neuron in the jth layer. 
        self.activations = activation from each neuron.
            activations[i,j] is the activation output by the ith neuron in the jth layer
        """
        weights = [];
        biases = [];
        Z = [];
        activations = [];
        for layer_num in range(1, self.num_layers):
            weights.append(np.random.randn(layers[layer_num], layers[layer_num - 1]));
            biases.append(np.random.randn(layers[layer_num]));
            Z.append(np.zeros(layers[layer_num]));
            activations.append(np.zeros(layers[layer_num]));
        self.weights = np.matrix(weights);
        self.biases = np.matrix(biases);
        self.Z = np.matrix(Z);
        self.activations = np.matrix(activations);
        """
        self.activation = string specifying what activation function the neurons will use. 
        The options are:
            sigmoid (default)
        """
        self.activation_function = activation_function;
        
    """ 
    ACTIVATION FUNCTION
    For this network, we use the sigmoid function to calculate neuron activation
    """      
    def activation(self, z):
        if (self.activation_function == "sigmoid"):
            return 1.0 / (1 + np.exp(-z));
    
    def activation_derivative(self, z):
        if (self.activation_function == "sigmoid"):
            return (1 - self.activation(z)) * self.activation(z);
        
    """
    TRAINING
    Train the network using stochastic gradient descent and backpropagation.
    Training data should be given in the following format:
        [x11, x12, ..., x1i, y1
         x21, x22, ..., x2i, y2
         ...
         xm1, xm1, ..., xmi, ym]
    Where each row corrsponds to a training example with i data points
    """
    def train(training_data, batch_size, num_epochs, learning_rate):
        for epoch in range(1, num_epochs):
            # Randomize the order of training examples
            np.random.shuffle(training_data);
            # Separate inputs from outputs
            inputs = training_data[:, :-1];
            outputs = training_data[:, -1];
            # For each epoch, loop through each batch to use as training data
            for batch in range(len(training_data))[0 :: batch_size]:
                # Create matrix out of all training inputs in the batch
                X = np.matrix(inputs[batch : batch + batch_size, :]); 
                Y = np.matrix(outputs[batch: batch + batch_size]);
                # We want to transpose X so that the ith column holds the data points
                # for the ith training example
                X = np.transpose(X);
                # FEEDFORWARD
                for layer in range(1, self.num_layers):
                    pass
                # Backpropagation
            
                # Gradient Descent
    
    """ 
    TODO: 
        test(testing_data)
    """
    def print_network(self):
        print("Weights: ")
        for layer in self.weights:
            print(layer)
        print("\nBiases:" )
        for layer in self.biases:
            print(layer)
        print("\nActivations:")
        for layer in self.activations:
            print(layer);

In [136]:
"""
TEST BATCH PARTITIONING
"""
batch_size = 2;
training_examples = np.matrix('1, 3, 5, 7; 2, 4, 6, 8 ; 10, 12, 14, 18; 20, 21, 22, 23');
inputs = training_examples[:, :-1];
outputs = training_examples[:,-1];
for batch in range(len(inputs))[0 :: batch_size]:
    X = np.matrix(inputs[batch : batch + batch_size, :])
    Y = np.matrix(outputs[batch: batch + batch_size])
    print(X)
    print(Y)
    print("\n")

print(outputs)
    

[[1 3 5]
 [2 4 6]]
[[7]
 [8]]


[[10 12 14]
 [20 21 22]]
[[18]
 [23]]


[[ 7]
 [ 8]
 [18]
 [23]]


In [144]:
"""
TEST NETWORK CREATION
"""
test = Simple_NN([3, 5, 2]);
test.print_network();

Weights: 
[[ array([[ 1.85701115,  1.05016641, -0.3568261 ],
       [-0.10482871,  0.60547991, -1.09448532],
       [ 1.1293635 , -2.21308706,  0.54724683],
       [ 2.77517515,  0.610776  ,  0.74211752],
       [ 2.11527701, -0.35603168,  2.10814426]])
  array([[ 1.12762617, -0.78380229,  1.10721175, -1.32314976, -0.44318806],
       [ 1.75516116,  0.31483771,  1.45535841, -0.63231052,  0.02339723]])]]

Biases:
[[array([-1.16950126, -1.42211871,  0.57253225,  1.1786072 ,  0.28252318])
  array([-0.7806755 ,  1.05819738])]]

Activations:
[[array([ 0.,  0.,  0.,  0.,  0.]) array([ 0.,  0.])]]
